=== hkamran80/assets/projects.schema.json
{
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "https://assets.hkamran.com/schema/projects",
    "title": "Projects",
    "description": "A list of projects for embedding",
    "type": "array",
    "uniqueItems": true,
    "items": {
        "type": "object",
        "properties": {
            "name": {
                "type": "string",
                "description": "The name of the project"
            },
            "description": {
                "type": "string",
                "description": "A short description of the project"
            },
            "featured": {
                "type": "boolean",
                "description": "Should the project be featured"
            },
            "repository": {
                "type": "string",
                "format": "uri",
                "description": "A link to the repository"
            },
            "url": {
                "type": "string",
                "format": "uri",
                "description": "A link to the project (not a repository link)"
            },
            "group": {
                "enum": ["apps", "tools", "directories", "bots"]
            },
            "owner": {
                "type": "object",
                "description": "The owner of the project, if not myself",
                "properties": {
                    "name": {
                        "type": "string"
                    },
                    "url": {
                        "type": "string",
                        "format": "uri",
                        "description": "A link to the owner's page"
                    }
                },
                "required": ["name"]
            },
            "role": {
                "type": "string",
                "description": "My role on the project"
            }
        },
        "required": ["name", "description", "group"],
        "dependentRequired": {
            "owner": ["role"]
        }
    }
}

=== hkamran80/assets/projects.json
[
    {
        "name": "Schedules",
        "description": "An app for all bell schedules. Know how much time is remaining in a period and when the next period starts.",
        "featured": true,
        "repository": "https://github.com/hkamran80/schedules",
        "url": "https://go.unisontech.org/sch",
        "group": "apps"
    },
    {
        "name": "Ramadan Taskminder",
        "description": "Stay on top of your tasks for Ramadan. Keep track of your Qur'an reading and other key tasks.",
        "featured": true,
        "repository": "https://github.com/hkamran80/ramadan-taskminder",
        "url": "https://13willow.com/project/ramadan-taskminder",
        "group": "apps"
    },
    {
        "name": "2FA Directory",
        "description": "A comprehensive directory of websites and services that support multi-factor authentication",
        "featured": true,
        "repository": "https://github.com/2factorauth/twofactorauth",
        "url": "https://2fa.directory",
        "group": "directories",
        "owner": {
            "name": "2factorauth",
            "url": "https://2factorauth-org.pages.dev"
        },
        "role": "Maintainer"
    },
    {
        "name": "Passkeys Directory",
        "description": "A comprehensive directory of websites and services that support passkeys",
        "featured": true,
        "repository": "https://github.com/2factorauth/passkeys",
        "url": "https://passkeys.2fa.directory",
        "group": "directories",
        "owner": {
            "name": "2factorauth",
            "url": "https://2factorauth-org.pages.dev"
        },
        "role": "Maintainer"
    },
    {
        "name": "TestFlight Cleaner",
        "description": "Clean your TestFlight tester CSVs and avoid dealing with those pesky errors!",
        "repository": "https://github.com/hkamran80/website/blob/redesign-nextjs/pages/program/testflight-cleaner.tsx",
        "url": "/utilities/testflight-cleaner",
        "group": "tools"
    },
    {
        "name": "Nebula New Tab",
        "repository": "https://github.com/hkamran80/nebula-new-tab",
        "url": "/projects/nebula-new-tab",
        "description": "A clean and simple new tab page",
        "group": "apps"
    },
    {
        "name": "Playlist Duplicator",
        "repository": "https://github.com/hkamran80/playlist_duplicator",
        "description": "A simple way to duplicate the contents of one Spotify playlist into another.",
        "group": "tools"
    }
]
